
INSERT INTO public.intelligence_rules (name, description, sport_type, is_active, priority, condition_type, condition_field, condition_operator, condition_value, action_type, action_target, created_by, conditions, actions) VALUES
('Softball Pitcher: Low Velocity', 'Fastpitch pitcher velocity below age-group average', 'softball', true, 10, 'kpi', 'pitch_speed', '<', 'age_group_avg', 'assign_drill', 'p-003', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"pitch_speed","operator":"<","value":"age_group_avg","period":"last_30_days"},{"field":"position","operator":"=","value":"pitcher"}]}',
 '[{"type":"assign_drill","target":"p-003","payload":{"reason":"Velocity below average"}},{"type":"flag_for_review","target":"coach","payload":{"message":"Pitcher velocity trending below average"}}]'),
('Softball Pitcher: Command Below 50%', 'Pitcher strike percentage below 50%', 'softball', true, 15, 'kpi', 'strike_percentage', '<', '50', 'assign_drill', 'p-004', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"strike_percentage","operator":"<","value":50}]}',
 '[{"type":"assign_drill","target":"p-004","payload":{"reason":"Command below 50%"}}]'),
('Softball Pitcher: Daily Overuse', 'Daily pitch count exceeds threshold', 'softball', true, 1, 'workload', 'daily_pitches', '>', 'age_threshold', 'trigger_alert', 'athlete', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"daily_pitches","operator":">","value":"age_threshold","period":"today"}]}',
 '[{"type":"trigger_alert","target":"athlete","payload":{"severity":"critical","message":"Daily pitch limit exceeded"}}]'),
('Softball Pitcher: Weekly Overuse', 'Weekly pitch count exceeds threshold', 'softball', true, 2, 'workload', 'weekly_pitches', '>', 'age_threshold', 'trigger_alert', 'athlete', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"weekly_pitches","operator":">","value":"age_threshold","period":"this_week"}]}',
 '[{"type":"trigger_alert","target":"athlete","payload":{"severity":"high","message":"Weekly pitch limit exceeded"}}]'),
('Softball Pitcher: Mechanics Risk', 'Injury-risk mechanics detected', 'softball', true, 3, 'mechanics', 'mechanics_flag', 'IN', 'elbow_bend_at_release,closed_hip_finish,hyperextended_stride,short_stride', 'trigger_alert', 'coach', '00000000-0000-0000-0000-000000000000',
 '{"logic":"OR","rules":[{"field":"mechanics_flag","operator":"IN","value":["elbow_bend_at_release","closed_hip_finish","hyperextended_stride","short_stride"]}]}',
 '[{"type":"trigger_alert","target":"coach","payload":{"severity":"critical","message":"Injury risk mechanics detected"}}]'),
('Softball Pitcher: Arsenal Gap', '14U+ with fewer than 3 pitches', 'softball', true, 20, 'kpi', 'arsenal_count', '<', '3', 'assign_drill', 'p-006', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"arsenal_count","operator":"<","value":3},{"field":"age_group","operator":">=","value":"14U"}]}',
 '[{"type":"recommend_course","target":"fastpitch-pitching-system","payload":{"reason":"Arsenal gap at 14U+"}}]'),
('Softball Catcher: Pop Time Slow', 'Pop time above age-group average', 'softball', true, 15, 'kpi', 'pop_time', '>', 'age_group_avg', 'assign_drill', 'f-003', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"pop_time","operator":">","value":"age_group_avg"}]}',
 '[{"type":"assign_drill","target":"f-003","payload":{"reason":"Pop time above average"}}]'),
('Softball Catcher: Blocking Low', 'Blocking save rate below 65%', 'softball', true, 15, 'kpi', 'blocking_save_rate', '<', '65', 'assign_drill', 'f-004', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"blocking_save_rate","operator":"<","value":65}]}',
 '[{"type":"assign_drill","target":"f-004","payload":{"reason":"Blocking save rate below 65%"}}]'),
('Softball Hitter: Bat Speed Low', 'Bat speed below age-group average', 'softball', true, 12, 'kpi', 'bat_speed', '<', 'age_group_avg', 'assign_drill', 'h-002', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"bat_speed","operator":"<","value":"age_group_avg"}]}',
 '[{"type":"assign_drill","target":"h-002","payload":{"reason":"Bat speed below average"}},{"type":"assign_drill","target":"h-004","payload":{"reason":"Overload/underload training"}}]'),
('Softball Hitter: Exit Velo Critical', 'Exit velocity in bottom tier', 'softball', true, 10, 'kpi', 'exit_velocity', '<', 'age_group_low', 'assign_drill', 'h-006', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"exit_velocity","operator":"<","value":"age_group_low"}]}',
 '[{"type":"assign_drill","target":"h-006","payload":{"reason":"Exit velocity critically low"}},{"type":"flag_for_review","target":"coach","payload":{"message":"Exit velocity bottom tier"}}]'),
('Softball IF: Throw Velo Low', 'Infielder throw velocity below avg', 'softball', true, 15, 'kpi', 'throw_velocity', '<', 'age_group_avg', 'assign_drill', 'f-003', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"throw_velocity","operator":"<","value":"age_group_avg"},{"field":"position","operator":"IN","value":"2B,SS,3B,1B"}]}',
 '[{"type":"assign_drill","target":"f-003","payload":{"reason":"Throw velocity below position average"}}]'),
('Softball OF: Arm Low', 'Outfielder arm strength below avg', 'softball', true, 15, 'kpi', 'throw_velocity', '<', 'age_group_avg', 'assign_drill', 'f-003', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"throw_velocity","operator":"<","value":"age_group_avg"},{"field":"position","operator":"IN","value":"LF,CF,RF"}]}',
 '[{"type":"assign_drill","target":"f-003","payload":{"reason":"Outfield arm below average"}}]'),
('Softball: Compliance Low', 'Training compliance below 50%', 'softball', true, 5, 'compliance', 'weekly_compliance', '<', '50', 'trigger_alert', 'coach', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"weekly_compliance","operator":"<","value":50}]}',
 '[{"type":"trigger_alert","target":"coach","payload":{"severity":"high","message":"Training compliance below 50%"}}]'),
('Softball: Dev Stalled', 'No KPI improvement in 30+ days', 'softball', true, 8, 'trend', 'kpi_improvement_count', '=', '0', 'trigger_alert', 'coach', '00000000-0000-0000-0000-000000000000',
 '{"logic":"AND","rules":[{"field":"kpi_improvement_count","operator":"=","value":0,"period":"last_30_days"}]}',
 '[{"type":"trigger_alert","target":"coach","payload":{"severity":"high","message":"No KPI improvement in 30+ days"}}]');
